import { Nav } from "@/components";
import "./globals.css";
import { Inter } from "next/font/google";
import AuthAdmin from "@/utils/AuthAdmin";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DVT Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="primary" lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthAdmin>
            <div className="flex flex-col lg:flex-row text-black bg-primary">
              <Nav />
              <div className="flex-1 bg-dvt-white-1 p-6 min-h-screen text-[#C2D0EA]">
                {children}
              </div>
            </div>
          </AuthAdmin>
        </Providers>
      </body>
    </html>
  );
}
